FLAG=--erc
./lem-in $FLAG < error/3_link_line.txt && echo 3_link_line.txt
./lem-in  $FLAG < error/bad_file.txt  && echo bad_file.txt
./lem-in $FLAG  <	error/begin_end_same.txt  && echo begin_end_same.txt
./lem-in $FLAG  < error/double_end.txt  && echo double_end.txt
./lem-in $FLAG  < error/double_link.txt  && echo double_link.txt
./lem-in $FLAG  < error/double_start.txt  && echo double_start.txt
./lem-in $FLAG  < error/double_vertex.txt  && echo double_vertex.txt
./lem-in $FLAG  < error/empty.txt  && echo empty.txt
./lem-in $FLAG  < error/empty_vertex_name.txt  && echo empty_vertex_name.txt
./lem-in $FLAG  < error/long_vertex_name.txt && echo long_vertex_name.txt
./lem-in $FLAG  < error/minus_ants.txt && echo minus_ants.txt
./lem-in $FLAG  < error/no_ants.txt && echo no_ants.txt
./lem-in $FLAG  < error/no_ants_empty_line.txt && echo no_ants_empty_line.txt
./lem-in $FLAG  < error/no_edges.txt && echo no_edges.txt
./lem-in $FLAG  < error/no_end.txt && echo no_end.txt
./lem-in $FLAG  < error/no_path.txt && echo no_path.txt
./lem-in $FLAG  < error/no_start.txt && echo no_start.txt
./lem-in $FLAG  < error/no_vertex.txt && echo no_vertex.txt
./lem-in $FLAG  < error/same_xy && echo same_xy
./lem-in $FLAG  < error/self_link.txt && echo self_link.txt
./lem-in $FLAG  < error/shortest_path.txt && echo shortest_path.txt
./lem-in $FLAG  < error/space_vertex_name.txt && echo space_vertex_name.txt
./lem-in $FLAG  < error/too_much_ants && echo too_much_ants
./lem-in $FLAG  < error/unknown_command.txt && echo unknown_command.txt
./lem-in $FLAG  < error/vertex_no_x.txt && echo vertex_no_x.txt
./lem-in $FLAG  < error/vertex_no_y.txt && echo vertex_no_y.txt
./lem-in $FLAG  < error/vertex_with_l.txt && echo vertex_with_l.txt
./lem-in $FLAG  < error/vertex_wrong_x.txt && echo vertex_wrong_x.txt
./lem-in $FLAG  < error/vertex_wrong_y.txt && echo vertex_wrong_y.txt
./lem-in $FLAG  < error/wrong_ants.txt && echo wrong_ants.txt
./lem-in $FLAG  < error/wrong_ants2.txt && echo wrong_ants2.txt
./lem-in  $FLAG < error/wrong_link.txt && echo wrong_link.txt
./lem-in $FLAG  < error/zero_ants.txt && echo zero_ants.txt
